### PR TITLE
Pin node dependency versions to be Specific/Fixed

### PR DESCRIPTION
**Pull request by SudharakaP**
Just noticed that our dependency version are not set to fixed versions in this repo. Suggest changing these to fixed versions as per our best practices; https://docs.opencollective.com/help/contributing/development/best-practice-guidelines#general-rules 😄

### CODE REVIEW

**Comment by znarf** [comment]
@SudharakaP If you're interested in this repository, could you maybe make sure the tests are passing first? It will be easier to merge other PRs next.

**Comment by SudharakaP** [comment]
> @SudharakaP If you're interested in this repository, could you maybe make sure the tests are generally passing first? It will be easier to merge PRs such as this one.

@znarf : Yes, I already made a fix for the tests issue at, https://github.com/opencollective/opencollective-images/pull/408. This should take care of the failing tests. Let me restart the tests in this PR. 😄

**Comment by SudharakaP** [comment]
@znarf : And as you see the tests are passing now. 😄

**Review by znarf — APPROVED** [review]

**Comment by SudharakaP** [comment]
@znarf : Just to note that I've re-based most of the other dependabot PRs as well and they are passing now; so you can merge them in the future.

**Pull request merged**
